import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
        <nav>
          <div class="logo-container">
            <img src="logos\png\logo-no-background.png" alt="AuditAI Logo" />
          </div>
          <div class="nav-links">
            <a href="#">Home</a>
            <a href="https://devpost.com">Devpost Submission</a>
            <a href="https://github.com/ukataria/Bitcamp2024">Github Repository</a>
            <a href="https://youtube.com">Youtube Video</a>
          </div>
      </nav>

      <div class="body">
        <h1>Audit AI</h1>
        <h2>Chat, Is This Real?</h2>
      </div>

      <div class = "game">
        <p>This is a game where you have 20 images, that you need to guess are generated by an AI or not. Play against our machine learning model, in a true human vs. machine test!</p>
        <h3>Correct Answers: 0</h3>
        <img src = "website/audit-ai/src/photos/pinterest-fake.jpg" alt="The Fake Image"/>
        <button>Real</button>
        <button>Fake</button>
      </div>

      {/* <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header> */}
    </div>
  );
}

export default App;
